name: Test Action

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    name: Test on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15-intel
          - macos-15
          - windows-2025

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install injm
        uses: ./

      - name: Verify injm
        shell: bash
        run: |
          injm --version
